# ModelArguments
model_name_or_path: ../models/openllama/3Bv2/
torch_dtype: float16
tokenizer_name: ../models/openllama/3Bv2/
# checkpoint: null
lora_config:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  target_modules:   # all
    - q_proj
    - k_proj
    - v_proj
tokenizer_kwargs:
  use_fast: False
  padding_side: right
  
# DataArguments
dataset_name: samsum

# Seq2SeqTrainingArguments
output_dir: openllama-3bv2-sft-lora8
num_train_epochs: 10
learning_rate: 0.0001  # 5e-5
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
per_device_eval_batch_size: 4
# fp16: True
bf16: True
adam_epsilon: 0.001 # 1e-3
lr_scheduler_type: cosine
weight_decay: 0.01  # 1e-2
optim: sgd  # adamw_torch
save_strategy: steps
evaluation_strategy: steps
logging_strategy: steps
eval_steps: 0.5
save_steps: 0.5
logging_steps: 0.05
save_total_limit: 3
load_best_model_at_end: True
report_to: tensorboard
remove_unused_columns: False  # https://discuss.huggingface.co/t/error-when-training-with-peft-lora/39958/2
# gradient_checkpointing=True
ddp_find_unused_parameters: False  # 
deepspeed: ds_config/ds_config_zero3.json