# ModelArguments
model_name_or_path: ../models/llama2/7B/
torch_dtype: float16
tokenizer_name: ../models/llama2/7B/
checkpoint: null
lora_config:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  target_modules:   # all
    - q_proj
    - k_proj
    - v_proj
tokenizer_kwargs:
  use_fast: False
  padding_side: right
  
# DataArguments
dataset_name: samsum

# Seq2SeqTrainingArguments
output_dir: llama2-7b-sft-lora8
num_train_epochs: 5
learning_rate: 0.0002
per_device_train_batch_size: 3
gradient_accumulation_steps: 5
per_device_eval_batch_size: 4
bf16: True
adam_epsilon: 0.001
lr_scheduler_type: cosine
weight_decay: 0.01
optim: adamw_torch  # sgd
save_strategy: steps
evaluation_strategy: steps
logging_strategy: steps
eval_steps: 0.5
save_steps: 0.5
logging_steps: 0.05
save_total_limit: 10
load_best_model_at_end: True
report_to: tensorboard
remove_unused_columns: False
# gradient_checkpointing: True  # 
ddp_find_unused_parameters: False
deepspeed: ds_config/ds_config_zero3.json